# Generated by Django 4.2.6 on 2023-10-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habits',
            name='related_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits'),
        ),
    ]
