# Generated by Django 4.2.6 on 2023-10-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='send_next_time',
            field=models.DateTimeField(help_text='Дата и время следующей отправки', null=True),
        ),
        migrations.AlterField(
            model_name='habits',
            name='author',
            field=models.ForeignKey(help_text='Автор привычки', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habits',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='how_long_seconds',
            field=models.PositiveIntegerField(help_text='Сколько секунд займёт выполнение привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='how_often_days',
            field=models.PositiveIntegerField(default=1, help_text='С какой периодичностью (дней) выполнять привычку'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='is_enjoyable',
            field=models.BooleanField(default=False, help_text='Привычка полезная?'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Привычка общедоступна?'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='related_habit',
            field=models.ForeignKey(help_text='С какой приятной привычкой связана привычка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='reward',
            field=models.TextField(help_text='Какое вознаграждение за выполнение привычки', null=True),
        ),
        migrations.AlterField(
            model_name='habits',
            name='what',
            field=models.TextField(help_text='Что из себя представляет привычка'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='when',
            field=models.TimeField(help_text='В какое время выполнять привычку', null=True),
        ),
        migrations.AlterField(
            model_name='habits',
            name='where',
            field=models.CharField(help_text='Где выполнять привычку', max_length=25),
        ),
    ]
